[project]
name = "pb-abc-and-proto-13-05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.15.0",
    "requests>=2.32.3",
]

[tool.mypy]
strict = true
